/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Wed Apr 14 2021 10:39:10 GMT-0500 (Central Daylight Time).
 */

define(['jointjs', 'css!./styles/PetriNetWidget.css'], function (joint) {
    'use strict';

    var WIDGET_CLASS = 'sim-s-m';

    function PetriNetWidget(logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');
    }

    PetriNetWidget.prototype._initialize = function () {
        console.log(joint);
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        // set widget class
        this._el.addClass(WIDGET_CLASS);

        this._petriNet = new joint.dia.Graph;
        this._jointPaper = new joint.dia.Paper({
            el: this._el,
            width : width,
            height: height,
            model: this._petriNet,
            interactive: false
        });

        // add event calls to elements
        this._jointPaper.on('element:pointerdblclick', function(elementView) {
            const currentElement = elementView.model;
            // console.log(currentElement);
            if (self._webgmePetriNet) {
                // console.log(self._webgmeSM.id2node[currentElement.id]);
                self._setCurrentState(self._webgmePetriNet.id2node[currentElement.id]);
            }
        });

        this._webgmePetriNet = null;
    };

    PetriNetWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    // Petri Net manipulating functions called from the controller
    PetriNetWidget.prototype.initPetriNet = function (netDescriptor) {
        const self = this;
        console.log(netDescriptor);

        self._webgmePetriNet = netDescriptor;
        self._webgmePetriNet.current = self._webgmePetriNet.init;
        self._petriNet.clear();
        const pn = self._webgmePetriNet;
        pn.id2node = {}; // this dictionary will connect the on-screen id to the state id
        // first add the places and transitions -- nodes
        Object.keys(pn.states).forEach(nodeId => {
            let vertex = null;
            if (pn.init === nodeId) { //place
                vertex = new joint.shapes.standard.Circle({
                    position: pn.nodes[nodeId].position,
                    size: { width: 20, height: 20 },
                    attrs: {
                        body: {
                            fill: '#333333',
                            cursor: 'pointer'
                        },
                        markings: pn.nodes[nodeId].markings,
                    }
                });
            } else { //transition
                vertex = new joint.shapes.standard.Rectangle({
                    size: { width: 20, height: 40 },
                    attrs: {
                        body: {
                            fill: '#99999',
                            cursor: 'pointer'
                        }
                    }
                });
            }
            vertex.addTo(self._petriNet);
            pn.nodes[nodeId].joint = vertex;
            pn.id2node[vertex.id] = nodeId;
        });

        // then create the links
        Object.keys(pn.nodes).forEach(nodeId => {
            const state = pn.nodes[nodeId];
            Object.keys(state.next).forEach(event => {
                state.jointNext = state.jointNext || {};
                const link = new joint.shapes.standard.Link({
                    source: {id: state.joint.id},
                    target: {id: pn.nodes[state.next[event]].joint.id},
                    attrs: {
                        line: {
                            strokeWidth: 2
                        },
                        wrapper: {
                            cursor: 'default'
                        }
                    },
                    labels: [{
                        position: {
                            distance: 0.5,
                            offset: 0,
                            args: {
                                keepGradient: true,
                                ensureLegibility: true
                            }
                        },
                        attrs: {
                            text: {
                                text: event,
                                fontWeight: 'bold'
                            }
                        }
                    }]
                });
                link.addTo(self._petriNet);
                state.jointNext[event] = link;
            })
        });

        //now refresh the visualization
        self._jointPaper.updateViews();
        self._decoratePetriNet();
    };

    PetriNetWidget.prototype.destroyMachine = function () {

    };

    PetriNetWidget.prototype.fireEvent = function (event) {
        const self = this;
        const current = self._webgmePetriNet.nodes[self._webgmePetriNet.current];
        const link = current.jointNext[event];
        const linkView = link.findView(self._jointPaper);
        linkView.sendToken(joint.V('circle', { r: 10, fill: 'black' }), {duration:500}, function() {
           self._webgmePetriNet.current = current.next[event];
           self._decoratePetriNet();
        });
    };

    PetriNetWidget.prototype.resetMachine = function () {
        this._webgmePetriNet.current = this._webgmePetriNet.init;
        this._decoratePetriNet();
    };

    PetriNetWidgetWidget.prototype._decoratePetriNet = function() {
        const pn = this._webgmePetriNet;
        Object.keys(pn.nodes).forEach(nodeId => {
            pn.nodes[nodeId].joint.attr('body/stroke', '#333333');
        });
        pn.nodes[pn.current].joint.attr('body/stroke', 'blue');
        pn.setFireableEvents(Object.keys(pn.nodes[pn.current].next));
    };

    PetriNetWidget.prototype._setCurrentState = function(newCurrent) {
        this._webgmePetriNet.current = newCurrent;
        this._decoratePetriNet();
    };
    

    /* * * * * * * * Visualizer event handlers * * * * * * * */

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    PetriNetWidget.prototype.destroy = function () {
    };

    PetriNetWidget.prototype.onActivate = function () {
        this._logger.debug('PetriNetWidget has been activated');
    };

    PetriNetWidget.prototype.onDeactivate = function () {
        this._logger.debug('PetriNetWidget has been deactivated');
    };

    return PetriNetWidget;
});
